version: "3.8"

services:
  postgresql:
    image: postgres:15
    container_name: postgresql
    restart: always
    env_file:
      - .env
    volumes:
      - ./.docker/postgres:/var/lib/postgresql/data
    ports:
      - ${POSTGRES_PORT}:5432
